services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=cuahangdientu
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data
